# -*- coding: utf-8 -*-
# -------------------------------------------------------------------------
# This file is part of the MindStudio project.
# Copyright (c) 2025-2026 Huawei Technologies Co.,Ltd.
#
# MindStudio is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          `http://license.coscl.org.cn/MulanPSL2`
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# -------------------------------------------------------------------------

import argparse
from textwrap import dedent


def setup_compare_parser(subparsers):
    compare_parser = subparsers.add_parser(
        'compare',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=dedent('''\
            COMPARE - Compare the results of multiple msprechecker dump runs.

            This command compares the outputs (JSON files) generated by previous runs of msprechecker dump.
            It highlights differences in both the main check results and configuration sections.

            Typical use cases:
              - Regression testing between different environments or code versions.
              - Verifying consistency across multiple deployments.
        '''),
        usage='msprechecker compare FILE1 FILE2 [FILE3 ...]',
        epilog=dedent('''\
            Examples:
              msprechecker compare result_a.json result_b.json
              msprechecker compare ./out1.json ./out2.json ./out3.json
        ''',
        ),
        help="  Compare the results of multiple msprechecker dump runs"
    )
    compare_parser.add_argument(
        'dumped_path',
        nargs='+',
        metavar='FILE',
        help='Paths to msprechecker output JSON files to compare (at least two required)'
    )
    return compare_parser
