# -------------------------------------------------------------------------
#  This file is part of the MindStudio project.
# Copyright (c) 2025 Huawei Technologies Co.,Ltd.
#
# MindStudio is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#
#          http://license.coscl.org.cn/MulanPSL2
#
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# -------------------------------------------------------------------------
from components.utils.parser import BaseCommand
from components.utils.security_check import check_input_path_legality, check_output_path_legality
from components.utils.log import set_log_level, LOG_LEVELS_LOWER
from msit_opcheck.opchecker import OpChecker
from msit_opcheck.autofuse.fusion_op_check import FuseOpChecker


class OpcheckCommand(BaseCommand):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.parser = None

    def add_arguments(self, parser, **kwargs):
        parser.add_argument(
            '--input',
            '-i',
            required=True,
            dest='input',
            type=check_input_path_legality,
            help='Configure the GE dump data path. In "single" mode, you can set it to the path '
                 'generated by the "msit debug dump" tool.')
        
        parser.add_argument(
            '--mode',
            '-m',
            required=False,
            dest='mode',
            default='single',
            choices=['single', 'autofuse'],
            help='Configure the opcheck scenario. Currently, two modes are supported: "single" and "autofuse".')
        # 当前msit debug dump对于自动融合场景不适配，因此需要手动指定graph路径
        parser.add_argument(
            '--graph-path',
            '-gp',
            required=False,
            dest='graph_path',
            type=check_input_path_legality,
            help='Configure the GE dump graph path.')

        parser.add_argument(
            '--output',
            '-o',
            required=False,
            dest='output',
            type=check_output_path_legality,
            default='./',
            help='Result data save directory. For example:--output /tmp/output.')
        
        parser.add_argument("--log-level", "-l", default="info", choices=LOG_LEVELS_LOWER, help="specify log level.")

    def handle(self, args):
        set_log_level(args.log_level)
        if args.mode == "single":
            opchecker = OpChecker(args)
        else:
            if not args.graph_path:
                raise ValueError("If the parameter '--mode' is set to 'autofuse', \
                                  it must be used together with parameter '--graph-path'.")
            opchecker = FuseOpChecker(args)
        opchecker.start_test()


def get_opcheck_cmd_ins():
    help_info = "Operation check tool for GE compile model."
    opcheck_instance = OpcheckCommand("opcheck", help_info)
    return opcheck_instance