env:
  CPU_AFFINITY_CONF:
    expected:
      type: eq
      value: "2"
    reason: "CPU 细粒度绑核"
  NPU_MEMORY_FRACTION:
    expected:
      type: eq
      value: "0.97"
    reason: "NPU内存占用比例，建议逐渐调高，但是太高会引起OOM"
  TASK_QUEUE_ENABLE:
    expected:
      type: eq
      value: "2"
    reason: "配置task_queue 算子下发队列优化登记，可能导致运行中NPU内存峰值上升"
  HCCL_OP_EXPANSION_MODE:
    expected:
      type: eq
      value: "AIV"
    reason: "配置通信算法的编排展开位置，代表通信算法的编排展开位置在 Device侧的 AI Vector Core 计算单元（MindIE 2.0.T3 和 MindIE 2.0.T3.1 使能 AIV 会有崩溃风险，请不要设置它）"
  HCCL_DETERMINISTIC:
    expected:
      type: eq
      value: "False"
    reason: "关闭确定性计算，只有在调试的时候才会需要打开"
  HCCL_RDMA_PCIE_DIRECT_POST_NOSTRICT:
    expected:
      type: eq
      value: "True"
    reason: "host bound 时性能有提升 (某些局点该环境变量和内核版本升级可以二选一)"
  MINDIE_LOG_LEVEL:
    expected:
      type: eq
      value: "ERROR"
    reason: "大量的日志打印是十分耗时的行为，且在正常的服务过程中，不需要这些日志"
    allow_undefined: true
  ASCEND_GLOBAL_LOG_LEVEL:
    expected:
      type: eq
      value: "3"
    reason: "大量的日志打印是十分耗时的行为，且在正常的服务过程中，不需要这些日志"
    allow_undefined: true
  ASCEND_LAUNCH_BLOCKING:
    expected:
      type: eq
      value: null
    reason: "关闭算子执行时启动同步模式（异步更快）"
  ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE:
    expected:
      type: eq
      value: "2"
    reason: "wordkpace 内存分配算法选择，可通过选择不同的算法测试workspace分配情况"
  ATB_WORKSPACE_MEM_ALLOC_GLOBAL:
    expected:
      type: eq
      value: "1"
    reason: "使用全局中间tensor 内存分配算法，会对中间tensor内存进行大小计算与分配"
  PYTORCH_NPU_ALLOC_CONF:
    expected:
      type: eq
      value: "expandable_segments:True"
    reason: "使能内存池扩展段功能，既虚拟内存特性；设置为True,可以优化内存碎片对内存的占用"

sys:
  high_performance:
    expected:
      type: "eq"
      value: true
    reason: "使 CPU 运行在最大频率下，可以提升 CPU 性能，但是会提高能耗"
    severity: "high"
  virtual_machine:
    expected:
      type: "eq"
      value: false
    reason: "虚拟机和物理机的 cpu 核数、频率有差异，会导致性能下降"
    severity: "high"
  transparent_hugepage:
    expected:
      type: "eq"
      value: "always"
    reason: "开启透明大页，吞吐率结果会更加稳定"
    severity: "high"
  release:
    expected:
      type: "ge"
      value: "Version(5.10)"
    reason: "升级到 5.10 以上，CPU 下发会加快，可以减少 host bound"
    severity: "high"

ascend:
  driver:
    version:
      expected:
        type: "ge"
        value: "Version(24.1)"
      reason: 升级到最新的驱动可以提升性能
      severity: "high"
