api-version: v1.0.0
metadata:
  config_id: default
  score: 50
  verified_model_types: []
  label:
    w_bit: 8
    a_bit: 8
    is_sparse: False
    kv_cache: False
spec:
  tokenizer_cfg:
    use_fast: False
    legacy: False
  model_cfg:
    low_cpu_mem_usage: True
  calib_cfg:
    w_bit: 8
    a_bit: 8
    mm_tensor: False
  calib_file: ../../calib_lab/boolq.jsonl
  calib_save_params:
    save_type:
      - 'ascendV1'
  






